# Generated by Django 3.1.3 on 2020-11-27 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('FacilityControl', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LogContent', models.CharField(max_length=254)),
                ('LogData', models.DateField()),
                ('Facility', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='FacilityControl.facility', to_field='UIN')),
            ],
        ),
    ]
