# Generated by Django 3.1.3 on 2020-11-20 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserControl', '0002_auto_20201120_1719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
    ]
