# Generated by Django 3.1.3 on 2020-11-24 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UIN', models.CharField(max_length=17, unique=True)),
                ('Name', models.CharField(max_length=254)),
                ('Description', models.CharField(max_length=254)),
                ('SerialNumber', models.CharField(max_length=254)),
                ('FirmwareVersion', models.CharField(max_length=254)),
                ('FirmwareLastUpdateDate', models.DateField()),
                ('DeviceEnabled', models.BooleanField(default=False)),
                ('DeviceMode', models.CharField(choices=[('off', 'Off'), ('one', 'One'), ('two', 'Two'), ('three', 'Three'), ('four', 'Four')], default='Off', max_length=254)),
                ('NetworkMode', models.CharField(choices=[('home', 'Home'), ('OneDevice', 'OneDevice')], max_length=254)),
                ('LastCO2Value', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('InUse', models.BooleanField(default=False)),
                ('NightModeEnabled', models.BooleanField(default=False)),
                ('NightModeAuto', models.BooleanField(default=False)),
                ('NightModeFrom', models.TimeField(null=True)),
                ('NightModeTo', models.TimeField(null=True)),
                ('DateCreated', models.DateField()),
                ('DateUpdated', models.DateField()),
            ],
        ),
    ]
